In [2]:
import numpy as np
import pandas as pd

In [4]:
d1=pd.DataFrame(np.random.randint(10,size=(2,2)),columns=['col1','col2'])
d1

col1  col2
0     8     7
1     0     8

In [6]:
t=np.zeros((5,2))
t

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
t1=np.arange(0,10,6)
t1

array([0, 6])

In [11]:
n1=np.array([1,2,3,4,5])
n1.sum()

15

In [12]:
n1.mean()

3.0

In [13]:
n1.std()

1.4142135623730951

In [14]:
n1.std()

1.4142135623730951

In [15]:
n1.max()

5

In [16]:
n1.min()

1

In [17]:
n1.argmax()

4

In [18]:
n1.argmin()

0

In [19]:
n1.var() #gives variance

2.0

In [21]:
#transposing
n2=n1.T
n2

array([1, 2, 3, 4, 5])

In [23]:
r=np.random.rand(2, 10, 10)
r

array([[[0.84667123, 0.71181053, 0.96678296, 0.82495654, 0.20203452,
         0.72008906, 0.31725964, 0.54938106, 0.92924256, 0.87423602],
        [0.56716209, 0.28076105, 0.91240688, 0.95975503, 0.77581697,
         0.16081462, 0.16755757, 0.87355903, 0.46809336, 0.18078796],
        [0.8123142 , 0.77805278, 0.78986135, 0.41951692, 0.58663901,
         0.53415076, 0.86959778, 0.58336904, 0.08834041, 0.03261139],
        [0.01712619, 0.26743177, 0.14180501, 0.74719925, 0.74553082,
         0.87542524, 0.01384927, 0.43095473, 0.24384236, 0.74949863],
        [0.20717058, 0.67124575, 0.07180904, 0.82887827, 0.30051207,
         0.70582799, 0.50181108, 0.70373341, 0.75532899, 0.7264644 ],
        [0.57565714, 0.43915623, 0.88695629, 0.42214408, 0.86783497,
         0.74757561, 0.19873998, 0.55109896, 0.14169263, 0.12600326],
        [0.17529213, 0.63008101, 0.3640888 , 0.1633771 , 0.84991395,
         0.81680163, 0.56092275, 0.43248238, 0.24920639, 0.19400756],
        [0.18029774, 0.5104

In [27]:
np.reshape(r,[5,1,-1])

array([[[0.84667123, 0.71181053, 0.96678296, 0.82495654, 0.20203452,
         0.72008906, 0.31725964, 0.54938106, 0.92924256, 0.87423602,
         0.56716209, 0.28076105, 0.91240688, 0.95975503, 0.77581697,
         0.16081462, 0.16755757, 0.87355903, 0.46809336, 0.18078796,
         0.8123142 , 0.77805278, 0.78986135, 0.41951692, 0.58663901,
         0.53415076, 0.86959778, 0.58336904, 0.08834041, 0.03261139,
         0.01712619, 0.26743177, 0.14180501, 0.74719925, 0.74553082,
         0.87542524, 0.01384927, 0.43095473, 0.24384236, 0.74949863]],

       [[0.20717058, 0.67124575, 0.07180904, 0.82887827, 0.30051207,
         0.70582799, 0.50181108, 0.70373341, 0.75532899, 0.7264644 ,
         0.57565714, 0.43915623, 0.88695629, 0.42214408, 0.86783497,
         0.74757561, 0.19873998, 0.55109896, 0.14169263, 0.12600326,
         0.17529213, 0.63008101, 0.3640888 , 0.1633771 , 0.84991395,
         0.81680163, 0.56092275, 0.43248238, 0.24920639, 0.19400756,
         0.18029774, 0.51040445

In [28]:
m1=np.array([10,2,11,34,15,6,2])
np.sort(m1)[::-1] #in descending order

array([34, 15, 11, 10,  6,  2,  2])

In [32]:
a2=np.random.randint(12,size=(3,4))
a2

array([[ 2,  8, 10,  6],
       [10,  8,  0,  2],
       [ 0,  7,  2,  8]])

In [33]:
a2[:,1:3]

array([[ 8, 10],
       [ 8,  0],
       [ 7,  2]])

In [34]:
a3=np.arange(0,15)
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
#negative indexing i want last 4 elements
a3[-1:-5:-1]

array([14, 13, 12, 11])

In [39]:
a3[-1:5:-1]

array([14, 13, 12, 11, 10,  9,  8,  7,  6])

In [40]:
a3[a3>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [41]:
a3[(a3>5) & (a3<10)]

array([6, 7, 8, 9])

In [42]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6]])


In [44]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [49]:
a = np.array((11,2,3))
b = np.array((4,5,6))
np.hstack((a,b))


array([11,  2,  3,  4,  5,  6])

In [50]:
np.vstack((a,b))

array([[11,  2,  3],
       [ 4,  5,  6]])

In [51]:
arr = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [54]:
ans=np.unique(arr,return_counts=True)
ans

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([3, 2, 2, 2, 1, 1, 1, 1, 1, 1], dtype=int64))

In [67]:
arr=np.ones((3,3))
arr[1:-1,1:-1]=0
arr

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

In [68]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6]])
#to check if 1d array is present or not in 2 array
np.in1d(a,b)

array([False, False, False, False])